const memoriam = [
	{
	name: 'Rick Booher',
	played: 'Drums',
	for: 'J. Michael Henderson',
	forLink: '/band/J_Michael_Henderson',
	date: '2013-03-18',
	reason: 'heart attack',
	},
	{
	name: 'Maurice James Whittemore, Jr.',
	played: 'Everything',
	for: '700 West',
	age: '87',
	date: '2022-01-20',
	reason: 'COVID',
	},
	{
	name: 'Dan Gustin',
	played: 'Vocals',
	for: 'Spectre',
	forLink: '/release/Spectre-WFBQ_Homegrown_Album_submission',
	date: '2021-08-14',
	reason: 'heart attack',
	},
	{
	name: 'Carl Haefli',
	played: 'Trumpet',
	for: 'Ebony Rhythm Funk Campaign',
	forLink: '/band/Ebony_Rhythm_Funk_Campaign',
	date: '1978',
	},
	{
	name: 'Jim Dicks',
	played: 'Bass, Vocals, Songwriter',
	for: 'Bronco, Granite, Sailor, Iron Horse',
	date: '1984',
	},
	{
	name: 'Herman Walker',
	played: 'Trumpet, Vocals',
	for: 'Amnesty, Ultimate Force',
	date: '?',
	},
	{
	name: 'Boobie Townsend',
	played: 'Guitar, Vocals',
	for: 'Ebony Rhythm Funk Campaign',
	forLink: '/band/Ebony_Rhythm_Funk_Campaign',
	date: '?',
	},
	{
	name: 'Jack Phelan',
	played: 'Bass',
	for: 'Studio musician',
	date: '2004',
	},
	{
	name: 'Rollin Wood',
	played: 'Percussionist',
	for: 'Roberts Owen, Maelstrom',
	forLink: '/band/Roberts_Owen',
	date: '2002',
	},
	{
	name: 'Bob Williams',
	played: "W'winds, K'bds, Songwriter",
	for: 'Maelstrom',
	forLink: '/band/Maelstrom',
	date: '2004',
	},
	{
	name: 'Tony Black',
	played: 'Vocalist',
	for: 'Ebony Rhythm Funk Campaign',
	forLink: '/band/Ebony_Rhythm_Funk_Campaign',
	date: '?',
	},
	{
	name: 'Kim Matchett',
	played: 'Percussionist',
	for: 'Malachi',
	forLink: '/band/Malachi',
	date: '?',
	},
	{
	name: 'Jim Haganman',
	played: 'Guitar',
	for: 'Malachi',
	forLink: '/band/Malachi',
	date: '?',
	},
	{
	name: 'Jack Schaefele',
	played: 'Saxophones',
	for: 'Malachi',
	forLink: '/band/Malachi',
	date: '2001',
	},
	{
	name: 'Bo Gooliak',
	played: "Bass, kybds; LA studio musician; 1 cut on 'Zerfas' LP",
	for: 'Peddler, Zerfas',
	forLink: '/band/Peddler',
	date: '2008-03-08',
	},
	{
	name: 'Larry Bryant',
	played: 'Multi-inst; vocals;songwriter',
	for: 'Broken Glass (gospel)',
	//forLink: '/band/Broken_Glass',
	date: '1990s (mid)',
	},
	{
	name: 'Charlie Smith',
	played: 'Guitar; vocals',
	for: 'Jubal; (+ others out of the area)',
	forLink: '/band/Jubal',
	date: '2008-02',
	},
	{
	name: 'Jeff Cobb',
	played: 'Guitar, vocals, songwriter',
	for: 'Aaron (+ others in area); Beatlesque original material',
	forLink: '/band/Aaron_Band',
	date: '2007-07-01',
	reason: 'cancer',
	},
	{
	name: 'Calvin Williams',
	played: 'Guitar',
	for: 'Amnesty, Ultimate Force',
	date: '2013-03',
	},
	{
	name: 'Jason Seidler',
	played: 'Guitar',
	for: 'Why On Earth',
	//forLink: '/band/Why_On_Earth',
	link: 'https://www.youtube.com/watch?v=VtCYGDW2_VM',
	linkText: 'Memoriam on youtube',
	date: '2011-07-16',
	},
	{
	name: 'Bill Rice',
	played: 'Bass',
	for: 'Zerfas/Jubal',
	date: '2003-05-30',
	},
	{
	name: 'Russell Peck',
	played: 'An award winning ASCAP composer',
	for: 'The Competition, Inc.',
	link: 'https://russellpeck.com',
	linkText: 'russellpeck.com',
	date: '2009',
	},
	{
	name: 'Gary Lee Brewer',
	played: "Gary was our 1st call session drummer because of his versatility. He did much session work and pub gigs in the area, but wasn't affiliated with any specific band",
	date: '2017-07-27',
	reason: 'heart attack',
	age: 63,
	for: "He played on some of my stuff from the 'MO' album, and was the drummer on Ed Ott's LP",
	},
	{
	name: 'Tommy Wills',
	played: 'Band leader.',
	date: '2017-10-21',
	reason: 'fall',
	age: '93',
	for: 'Tommy Wills band',
	forLink: '/band/Tommy_Wills',
	},
	{
	name: 'James Massie',
	played: 'Bassist',
	date: '2017-11-12',
	age: '63',
	for: 'Amnesty, Rapture',
	},
	{
	name: 'Eugene Blakey',
	played: 'Songwriter, vocals, keyboard',
	date: '2007-12-25',
	for: 'Blakey Special',
	forLink: '/band/Blakey_Special',
	},
	{
	name: 'Steve Newbold',
	played: 'Guitarist, backup vocals',
	date: '2018-04-23',
	reason: 'heart attack',
	age: '63',
	for: 'Zerfas',
	forLink: '/band/Zerfas',
	},
	{
	name: 'Howard Phillips',
	played: 'Percussion',
	date: '2019-07-17',
	for: 'Jubal/Zerfas',
	forLink: '/band/Zerfas',
	},
	{
	name: 'Matthew Watson',
	played: 'drums',
	date: '2019-09-07',
	for: 'Ebony Rhythm Funk Campaign, Epoxy, 700 West session musician.',
	link: 'https://www.youtube.com/watch?v=NdBmu_sqsH0',
	linkText: '2007 ERFC Reunion drum solo.',
	}
];

export default memoriam;
